[package]
name = "solana-lints"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
tempfile = "3.3.0"
toml = "0.6.0"

[package.metadata.rust-analyzer]
rustc_private = true
